### ISSUE TITLE
Error: Unknown variables

### ISSUE THREAD

**Issue by Brenndoerfer** [dunovank/jupyter-themes#182] opened 2017-09-27 18:25 UTC
When I want to switch to some themes
e.g. `jt -t monokai` or also `solarizedl` I get following error.

```
Traceback (most recent call last):
  File "/Users/michael/anaconda/envs/deeplearning/bin/jt", line 11, in <module>
    sys.exit(main())
  File "/Users/michael/anaconda/envs/DeepLearning/lib/python3.6/site-packages/jupyterthemes/__init__.py", line 305, in main
    dfonts=args.defaultfonts)
  File "/Users/michael/anaconda/envs/DeepLearning/lib/python3.6/site-packages/jupyterthemes/__init__.py", line 101, in install_theme
    style_css = stylefx.less_to_css(style_less)
  File "/Users/michael/anaconda/envs/DeepLearning/lib/python3.6/site-packages/jupyterthemes/stylefx.py", line 63, in less_to_css
    style_css = lesscpy.compile(tempfile)
  File "/Users/michael/anaconda/envs/DeepLearning/lib/python3.6/site-packages/lesscpy/__init__.py", line 18, in compile
    p.parse(file=file)
  File "/Users/michael/anaconda/envs/DeepLearning/lib/python3.6/site-packages/lesscpy/lessc/parser.py", line 157, in parse
    self.register.close()
  File "/Users/michael/anaconda/envs/DeepLearning/lib/python3.6/site-packages/lesscpy/lessc/parser.py", line 44, in __close__
    raise CompilationError("\n".join(self.errors))
lesscpy.exceptions.CompilationError: E: line: 0: Unknown variable @nb-header-fg

E: line: 0: Unknown variable @nb-header-fg

E: line: 0: Unknown variable @button-hover-border

E: line: 0: Unknown variable @button-hover-border

E: line: 0: Unknown variable @button-focus-fg

E: line: 0: Unknown variable @button-focus-fg

E: line: 0: Unknown variable @button-focus-bg

E: line: 0: Unknown variable @button-hover-bg

E: line: 0: Unknown variable @form-input-border

E: line: 0: Unknown variable @code-fg

E: line: 0: Unknown variable @code-fg

E: line: 0: Unknown variable @code-fg

E: line: 0: Unknown variable @md-header-link

E: line: 0: Unknown variable @button-hover-bg

```

**Comment by aysark** [comment] 2017-09-28 04:24
Running into this issue too, tried Python 2.7 and 3.6.  My $PYTHONPATH is not empty.

**Comment by vindev01** [comment] 2017-09-28 07:24
Facing the same issue on 3.6 anaconda distribution. 
"grade3", "oceans16" and "onedork" however applies fine. No luck with the rest of the themes.
Tried uninstalling and re-installing & --upgrade. Installation is smooth w/o errors.

**Comment by dunovank** [comment] 2017-09-28 15:36
thanks for the feedback y'all, this was a total mental lapse on my part, forgot to update some of the style sheets with new less variables. I'll try to resolve by the end of the week and will post an update here when I release a fixed version. Thanks again and sorry for the trouble!

**Comment by dunovank** [comment] 2017-10-01 04:48
Okay hopefully the issue is fixed. Would someone mind confirming by upgrading to `v0.18.0`?
```
pip install --upgrade jupyterthemes
```

**Comment by shiman** [comment] 2017-10-01 05:21
Thanks @dunovank It now woks like a charm

**Comment by dunovank** [comment] 2017-10-01 22:01
wonderful, thanks! closing.

**Closed by dunovank** 2017-10-01 22:01 UTC
