### ISSUE TITLE
An Option to set font size of Mathematical Symbols

### ISSUE THREAD

**Issue by bhanubais** [dunovank/jupyter-themes#163] opened 2017-08-14 12:12 UTC
Currently all Font size of mathematical objects are quite small. I can increase it's size by using `-tfs <font-size>` but it also increases normal text's size.
I think this There is feature which is missing but very easy to integrate A flag for only "Font size of Mathematical Symbols" e.g.  

`jt -t grade3 -fm 15`

If we hit this command font size of mathematical object should be changed to 15px.

**Comment by dunovank** [comment] 2017-09-08 20:35
I'll add this in the next release, thanks for the input! Will use the flag `-mathfs` (mathfontsize)

**Comment by bhanubais** [comment] 2017-09-18 03:34
Hi dunovank,
Thanks for implementing mathfontsize flag. But It is not still working. It only increasing the line height of mathematical fonts instead of font-size.

**Comment by dunovank** [comment] 2017-09-22 02:19
ahh sorry about that, I'll reopen the issue then and post an update when fixed. thanks!

**Comment by dunovank** [comment] 2017-09-27 14:10
closing this (duplicate of #175 )

**Closed by dunovank** 2017-09-27 14:10 UTC
