### ISSUE TITLE
Unclear instructions about missing toolbar

### ISSUE THREAD

**Issue by demidovakatya** [dunovank/jupyter-themes#12] opened 2016-01-31 15:30 UTC
Okay, I've installed jupyter-themes, [picked a theme and installed](https://github.com/dunovank/jupyter-themes#pick-a-theme-and-install), launched my notebook... toolbar's gone. 

Someone had the same problem, anf you said they needed to add some lines. You've also mentioned it in the Readme file, but *before* installation or anything else instructions. Whyyyy

I've also commented lots of lines with `div#maintoolbar {display: none !important;}`, but it didn't help.

I'm going to do something about the instructions, if you help me with understanding wtf is going on, I'll be happy :balloon: :smile:

**Comment by demidovakatya** [comment] 2016-01-31 15:39
Okay, I've fixed what bothered me the most in #13

**Comment by demidovakatya** [comment] 2016-01-31 15:44
LOL

I've just deleted the whole file `custom.css` (in `/Users/mac/.jupyter/custom`) – and I've got my default white Ipython notebook back!

**Comment by dunovank** [comment] 2016-01-31 21:29
Yes, there is an issue with toggling on/off the toolbar. I'm currently too busy to fix it, but there are also some other contributors looking into this. Also the order of the readme instructions are as intended. This informs the user about the toolbar being removed by default so they can factor this into deciding whether or not to install the package. Closing.

**Closed by dunovank** 2016-01-31 21:29 UTC

**Comment by demidovakatya** [comment] 2016-01-31 22:00
I hope you'll have a good rest when you are not so busy. :)
