### ISSUE TITLE
Unable to see cell number, cell type: IN or OUT

### ISSUE THREAD

**Issue by shravankumar147** [dunovank/jupyter-themes#206] opened 2017-11-26 09:41 UTC
![image](https://user-images.githubusercontent.com/9673411/33238859-15cabc5e-d2bc-11e7-9290-dacc2cbec665.png)

**Comment by Dirguis** [comment] 2017-12-03 20:14
On the left side of the cell, the number: `In [execution number]:` is missing

**Comment by wiseyoungbuck** [comment] 2018-01-31 16:25
This may be due to you having the `-altp` flag enabled. I don't know if this is expected behavior or not, but I had the same problem and it went away when stopped using that option.

**Comment by dunovank** [comment] 2018-02-25 03:42
Thanks @wiseyoungbuck. Closing this.

**Closed by dunovank** 2018-02-25 03:42 UTC

**Comment by amansingh9097** [comment] 2019-04-26 06:31
I never used `-altp` but I'm still not able to view the cell number. Its difficult to identify whether the cell block is still executing or not.<br> I used the following command in the notebook `!jt -t gruvboxd -T -kl -P -N` <br> Please find attached below a screenshot of the same.
![jt_bug](https://user-images.githubusercontent.com/19652765/56787682-ed3ac180-681a-11e9-9f7e-f355109d1746.jpg)
