### ISSUE TITLE
Failed to install theme

### ISSUE THREAD

**Issue by jojonki** [dunovank/jupyter-themes#156] opened 2017-07-21 14:16 UTC
I let you know `jt -t` command was not working in my windows environment. Please see below error message. And the error is translated to English by me because the error is printed in Japanese. I also tried to open my terminal as Administration mode, but same error occurred. 
```
$ jt -t onedork
Traceback (most recent call last):
  File "c:\users\jonki\anaconda3\lib\runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\jonki\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\jonki\Anaconda3\Scripts\jt.exe\__main__.py", line 9, in <module>
  File "c:\users\jonki\anaconda3\lib\site-packages\jupyterthemes\__init__.py", line 285, in main
    dfonts=args.defaultfonts)
  File "c:\users\jonki\anaconda3\lib\site-packages\jupyterthemes\__init__.py", line 103, in install_theme
    stylefx.remove_temp_file()
  File "c:\users\jonki\anaconda3\lib\site-packages\jupyterthemes\stylefx.py", line 77, in remove_temp_file
    os.remove(tempfile)
PermissionError: [WinError 32] Cannot access the profile. Another process is currently using: 'C:\\Users\\jonki\\AppData\\Local\\Temp\\tmpm_5sf7fo.less'
```

**My environment**
- windows 10
- Python 3.5.2, Anaconda 4.1.1 (64-bit)
- jupyterthemes 0.17.0

**Temporary fix**
Comment out `os.remove` temporary. Then installation will succeed.
```
def remove_temp_file():
    # remove tempfile.less
    #os.remove(tempfile)
    pass

```

**Comment by dunovank** [comment] 2017-07-21 14:24
Thanks for this, it'll be fixed in v0.17.1 (releasing in the next couple mins)

**Comment by dunovank** [comment] 2017-07-21 15:16
[re-opening until confirmed fix]. Realized this was a duplicate of #155 . Hoping this issue has been fixed in version 0.17.3. Would you mind updating to the newest release and posting back here if the issue has been resolved or not? 

`pip install --upgrade jupyterthemes`

**Comment by jojonki** [comment] 2017-07-22 05:26
I updated to 0.17.3, then I could execute `jt -t` without error. Thank you!

**Comment by dunovank** [comment] 2017-07-22 19:10
Good to hear, thanks. Closing

**Closed by dunovank** 2017-07-22 19:10 UTC
