### ISSUE TITLE
Adding solarized-light theme

### ISSUE THREAD

**Issue by svendx4f** [dunovank/jupyter-themes#65] opened 2016-10-13 22:41 UTC
Hi, 

Thanks for developing jupyter-themes, that's a very nice little tool! 

I forked your repo and started working on a port of the [Solarized-light theme of Ethan Schoonover](http://ethanschoonover.com/solarized). 

Would you welcome a PR from me contributing this theme to your project (if yes, I'll also contact Ethan Schoonover to see how he feels about that)? 

I'm not completely finished yet but the current result looks pretty good already, IMHO: 

![image](https://cloud.githubusercontent.com/assets/1214071/19369539/636c2a18-91a6-11e6-9bd5-7f5fd9fa67ea.png)

![image](https://cloud.githubusercontent.com/assets/1214071/19369571/902af7fa-91a6-11e6-8c60-7c6351a588b9.png)

![image](https://cloud.githubusercontent.com/assets/1214071/19369580/a09fee06-91a6-11e6-9015-021e513eb593.png)

Please let me know what you think

**Comment by dunovank** [comment] 2016-10-15 00:24
Thanks, and looks great! Totally welcome a pull request whenever you're ready. If I'm slow to accept it's because I'm busy screaming at my dissertation. Will try my best to act in a timely fashion....

Thanks for getting in touch, looking forward to have more outside contributions!

**Comment by svendx4f** [comment] 2016-10-24 09:48
Thanks for the encouragements @dunovank . 
I understand you're super busy with your dissertation. When do you think you'll find some time to  have a look at [this PR](https://github.com/dunovank/jupyter-themes/pull/69) ? It's super short and quickly validated (I think), and I see this as a first step for the solarized theme. 
Thanks!

**Comment by carlthome** [comment] 2016-10-24 11:59
Looks great!

**Comment by dunovank** [comment] 2016-12-14 17:16
@svendx4f just merged your PR for applying theme to auto-complete menu ( #69 ) .

**Comment by xiaohk** [comment] 2016-12-20 20:11
This theme looks pretty good!

**Comment by svendx4f** [comment] 2016-12-20 21:14
Thanks for the merge @dunovank, I hope the defence of your dissertation went well?
I continued working on the solarized theme in the meanwhile, see the PR above, I think it's less dark and easier to read than in my original screenshots. I hope you guys like it :)

**Comment by dunovank** [comment] 2017-01-06 23:52
Hey @svendx4f , thanks for all the work on that PR. I just confirmed the merge, will be included in the next release (available soon).  And yes, dissertation defense went great, enjoying the post-doc life now ;) 

Thanks again!

**Closed** 2017-01-06 23:52 UTC
