### ISSUE TITLE
Font directories missing

### ISSUE THREAD

**Issue by N2ITN** [dunovank/jupyter-themes#58] opened 2016-08-26 22:37 UTC
Just upgraded to the recent version, now fonts are missing that previously worked.

'IOError: [Errno 2] No such file or directory: 'C:\\Users\\zeste\\.jupyter\\custom\\fonts\\droidmono\\droid-sans-mono.woff''

The C:\Users\zeste\.jupyter\custom\fonts is empty (not sure if it was before the upgrade)

**Comment by dunovank** [comment] 2016-08-27 08:42
Hm... Would you mind posting the input and the full error?

**Comment by jebarb** [comment] 2016-08-29 15:35
Same issue here. Full error output:
`[W 11:32:24.989 NotebookApp] 404 GET /custom/fonts/exo-II-regular.ttf (::1) 7.96ms referer=http://localhost:8889/custom/custom.css
[W 11:32:28.553 NotebookApp] 404 GET /custom/fonts/exo-II-regular.ttf (::1) 1.27ms referer=http://localhost:8889/custom/custom.css
[W 11:32:29.414 NotebookApp] 404 GET /custom/fonts/firacode.otf (::1) 1.59ms referer=http://localhost:8889/custom/custom.css
[W 11:32:29.418 NotebookApp] 404 GET /custom/fonts/droid-sans-mono.woff (::1) 1.29ms referer=http://localhost:8889/custom/custom.css
`
Last three lines came when actually trying to open a notebook, first came up when browser was initially opened.

FWIW, I'm running Arch. To replicate, install jupyter-notebook, install jupyter-themes with pip, and launch jupyter-notebook from terminal.

**Comment by dunovank** [comment] 2016-08-31 00:22
I'm having trouble replicating the error. Any of the following feedback would help:

- Have you tried re-installing a theme via the CL since upgrading? 
- Does ~/.jupyter/custom/fonts/ exist? If so, is it missing the files for the fonts in question? 
- Do you get any errors when trying to install a theme? Or does the theme get installed without the requested fonts? 
- If installing a theme via CL seems to work, would one of you mind uploading the custom.css file in ~/.jupyter/custom or copy/pasting the first ~50 lines of that file. 

Sorry for the headache, and thanks for being patient while I figure out the bug!

**Comment by jebarb** [comment] 2016-08-31 00:30
Tried reinstalling the theme and jupyter as a whole, after deleting all config files. Looks like the issue is the fonts aren't being moved into the ~/.jupyter/custom/fonts/ directory. I don't get any errors or warnings other than the ones from above. Checked the custom.css against the css for the theme I was using and it's the same.

Still getting the errors that come after the fonts and jupyter is still frozen for about 20 seconds.

**Comment by N2ITN** [comment] 2016-08-31 00:36
Tried moving the fonts to the ~/.juypter/custom/fonts directory and get the following error:

```
C:\Users\zeste>jt -t chesterish
Traceback (most recent call last):
  File "c:\users\zeste\anaconda2\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\users\zeste\anaconda2\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Users\zeste\Anaconda2\Scripts\jt.exe\__main__.py", line 9, in <module>
  File "c:\users\zeste\anaconda2\lib\site-packages\jupyterthemes\__init__.py", line 85, in main
    install_theme(args.theme, monofont=args.monofont, monosize=args.monosize, nbfont=args.nbfont, nbfontsize=args.nbfontsize, tcfont=args.tcfont, tcfontsize=args.tcfontsize, cellwidth=int(args.cellwidth), lineheight=int(args.lineheight), cursorwidth=args.cursorwidth, cursorcolor=args.cursorcolor, altlayout=args.altlayout, vimext=args.vimext, toolbar=args.toolbar, nbname=args.nbname)
  File "c:\users\zeste\anaconda2\lib\site-packages\jupyterthemes\__init__.py", line 38, in install_theme
    stylefx.reset_default(False)
  File "c:\users\zeste\anaconda2\lib\site-packages\jupyterthemes\stylefx.py", line 319, in reset_default
    delete_font_files()
  File "c:\users\zeste\anaconda2\lib\site-packages\jupyterthemes\stylefx.py", line 84, in delete_font_files
    os.remove(abspath)
WindowsError: [Error 5] Access is denied: 'C:\\Users\\zeste\\.jupyter\\custom\\fonts\\monospace'
```

**Comment by dunovank** [comment] 2016-08-31 00:39
what version of python are you running?

**Comment by N2ITN** [comment] 2016-08-31 00:39
For reference the original error  I posted in full:


`C:\Users\zeste>jt -t chesterish
Traceback (most recent call last):
  File "c:\users\zeste\anaconda2\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\users\zeste\anaconda2\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Users\zeste\Anaconda2\Scripts\jt.exe\__main__.py", line 9, in <module>
  File "c:\users\zeste\anaconda2\lib\site-packages\jupyterthemes\__init__.py", line 85, in main
    install_theme(args.theme, monofont=args.monofont, monosize=args.monosize, nbfont=args.nbfont, nbfontsize=args.nbfontsize, tcfont=args.tcfont, tcfontsize=args.tcfontsize, cellwidth=int(args.cellwidth), lineheight=int(args.lineheight), cursorwidth=args.cursorwidth, cursorcolor=args.cursorcolor, altlayout=args.altlayout, vimext=args.vimext, toolbar=args.toolbar, nbname=args.nbname)
  File "c:\users\zeste\anaconda2\lib\site-packages\jupyterthemes\__init__.py", line 45, in install_theme
    style_less = stylefx.set_font_properties(monofont=monofont, monosize=monosize, nbfont=nbfont, nbfontsize=nbfontsize, tcfont=tcfont, tcfontsize=tcfontsize)
  File "c:\users\zeste\anaconda2\lib\site-packages\jupyterthemes\stylefx.py", line 189, in set_font_properties
    style_less = import_stored_fonts(style_less, fontcodes=[nbfont, tcfont, monofont, 'firacode'])
  File "c:\users\zeste\anaconda2\lib\site-packages\jupyterthemes\stylefx.py", line 172, in import_stored_fonts
    style_less = import_fonts(style_less, fname, fpath)
  File "c:\users\zeste\anaconda2\lib\site-packages\jupyterthemes\stylefx.py", line 223, in import_fonts
    send_fonts_to_jupyter(os.path.join(fontpath, fontfile))
  File "c:\users\zeste\anaconda2\lib\site-packages\jupyterthemes\stylefx.py", line 79, in send_fonts_to_jupyter
    copyfile(font_file_path, os.path.join(jupyter_custom_fonts, fname))
  File "c:\users\zeste\anaconda2\lib\shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 2] No such file or directory: 'C:\\Users\\zeste\\.jupyter\\custom\\fonts\\droidmono\\droid-sans-mono.woff'`

**Comment by N2ITN** [comment] 2016-08-31 00:39
2.7 on Anaconda

**Comment by jebarb** [comment] 2016-08-31 00:46
Also on 2.7

**Comment by dunovank** [comment] 2016-09-15 23:47
Has anyone tried the update? Wondering if the font directories are still breaking..

**Comment by dunovank** [comment] 2016-10-05 18:32
Assuming this has been resolved. Closing.

**Closed by dunovank** 2016-10-05 18:32 UTC
